services:

  besu-validator5:
    image: hyperledger/besu:26.4.0@sha256:12e256a73185337f2d09fa00c6a979d9ce9a8aac4ec1e173c43f3ef88443a799
    container_name: ds-besu-validator5
    volumes:
      - ./Layer1/besu/config.toml:/config/config.toml:ro
      - ./Layer1/besu/genesis.json:/config/genesis.json:ro
      - ./Layer1/besu/nodes/validator5/data:/opt/besu/data
    command:
      - --config-file=/config/config.toml
      - --bootnodes=enode://dc76e6b0726de575578083be78c894b0cef638c1d05bfe38f6cb8f2d02822f7010fc08c59fabd717cd9410b6a8f808319f4d4ef86a29cd1ea2c6245c147eebe1@172.30.0.11:30303
      - --metrics-enabled
      - --metrics-host=0.0.0.0
      - --metrics-port=9545
      - --metrics-category=BLOCKCHAIN,ETHEREUM,PEERS,TRANSACTION_POOL,SYNCHRONIZER,PROCESS,JVM
    depends_on:
      besu-validator1:
        condition: service_healthy
    networks:
      appchain:
        ipv4_address: 172.30.0.19
